### ISSUE TITLE
xgql does not deduplicate query keys

### ISSUE THREAD

**Issue by negz** [upbound/xgql#78]
### What happened?

```gql
{
  kubernetesResource(id: "Hi8wQzg9X0M4XYY8YVZQVQE") {
    metadata {
      name
    }
    ... on CompositeResourceDefinition {
      metadata {
        uid
      }
    }
  }
}
```

Yields this:
```json
{
  "data": {
    "kubernetesResource": {
      "metadata": {
        "name": "compositeclusters.aws.platformref.crossplane.io"
      },
      "metadata": {
        "uid": "a8dcfa8e-3909-4bf8-968b-64c65ca9b65b"
      }
    }
  }
}
```

Which is invalid JSON and should yield this:
```json
{
  "data": {
    "kubernetesResource": {
      "metadata": {
        "name": "compositeclusters.aws.platformref.crossplane.io",
        "uid": "a8dcfa8e-3909-4bf8-968b-64c65ca9b65b"
      }
    }
  }
}
```

This may be related https://github.com/99designs/gqlgen/issues/1311.

### How can we reproduce it?

Make the query above.

**Comment by negz** [comment]
I tried this with https://github.com/99designs/gqlgen/commit/5ad012e3d7be1127706b9c8a3da0378df3a98ec1, which is the latest commit in master at the time of writing. It appears to fix the problem of returning duplicate keys, but it does so by having the inline fragment _override_ the more generic part of the query rather than merging them. That is, if I query:

```gql
query {
  kubernetesResource(
    id: "Xf5rXAL-UHvndETH56dPJgA5XXvndEQ5PV9DOf4zbf43O1X_Bzg1MDkxNzM"
  ) {
    metadata {
      name
    }
  }
}
```

I get this response:

```gql
{
  "data": {
    "kubernetesResource": {
      "metadata": {
        "name": "crossplane-provider-aws-3b7ef8509173"
      }
    }
  },
  "extensions": {}
}
```

However if I query:

```gql
query {
  kubernetesResource(
    id: "Xf5rXAL-UHvndETH56dPJgA5XXvndEQ5PV9DOf4zbf43O1X_Bzg1MDkxNzM"
  ) {
    metadata {
      name
    }
    ...on ProviderRevision {
      metadata {
        uid
      }
    }
  }
}
```

I get:

```gql
{
  "data": {
    "kubernetesResource": {
      "metadata": {
        "uid": "3c3d2f11-cf1a-4f49-8e53-88a1110a352c"
      }
    }
  },
  "extensions": {}
}
```

**Comment by negz** [comment]
I presume the above behaviour is not intended and is still a bug in gqlgen, because this query merges the `metadata` response into a single object as you'd expect:

```gql
query {
  kubernetesResource(
    id: "Xf5rXAL-UHvndETH56dPJgA5XXvndEQ5PV9DOf4zbf43O1X_Bzg1MDkxNzM"
  ) {
    metadata {
      name
    }
		metadata {
      uid
    }
  }
}
```

**Comment by negz** [comment]
I've raised https://github.com/99designs/gqlgen/issues/1547 to track this.

**Comment by negz** [comment]
It's far from ideal, but I wonder whether it's possible to work around the "new" version of this bug (i.e. where inline fragments override less specific queries) by duplicating the information we want inside inline fragments. For example:

```gql
query {
  kubernetesResource(
    id: "Xf5rXAL-UHvndETH56dPJgA5XXvndEQ5PV9DOf4zbf43O1X_Bzg1MDkxNzM"
  ) {
    metadata {
      name
    }
    ...on ProviderRevision {
      metadata {
        # We duplicate name here to make sure it's always returned.
        name
        uid
      }
    }
  }
}
```

**Comment by thephred** [comment]
Our use of xgql is through a stitching layer that auto-generates fragments. Not having control of these fragments is why this and the original bug are hard to deal with. At least with the original bug the data was in the payload, just spread among duplicate keys. In this new bug they data is just missing.
